---
name: Create Jenkins service directory
ansible.builtin.file:
  path: "{{ jenkins_service_dir }}"
  state: directory
  mode: '0755'

name: Create Jenkins data directory
ansible.builtin.file:
  path: "{{ jenkins_data_dir }}"
  state: directory
  mode: '0755'

name: Generate Docker Compose file for Jenkins
ansible.builtin.template:
  src: docker-compose.yml.j2
  dest: "{{ jenkins_service_dir }}/docker-compose.yml"
  mode: '0644'

name: Start Jenkins with Docker Compose
community.docker.docker_compose:
  project_src: "{{ jenkins_service_dir }}"
  state: present
  pull: yes
  recreate: smart
