# ansible/playbooks/roles/docker/tasks/main.yml
---
- name: Update apt cache and install prerequisites
  ansible.builtin.apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture | default('amd64') }}]
      https://download.docker.com/linux/debian
      {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: ansible_user is defined

- name: Ensure docker-compose binary is absent (cleanup legacy standalone)
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    state: absent
