# ansible/playbooks/roles/k3s/tasks/main.yml
---
- name: Check if k3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Download k3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'
  when: not k3s_binary.stat.exists

- name: Install k3s
  ansible.builtin.command:
    cmd: /tmp/k3s_install.sh
    creates: /usr/local/bin/k3s
  when: not k3s_binary.stat.exists

- name: Ensure k3s service is enabled and running
  ansible.builtin.systemd:
    name: k3s
    enabled: true
    state: started
