version: '3.8'

services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - /opt/docker/data/jdownloader/config:/config:rw
      - /opt/jdownloader/downloads:/output:rw
    restart: unless-stopped
    
