---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - CLI_ARGS= #optional
    volumes:
      - /opt/docker/data/duplicati/config:/config
      - /opt/backups:/backups
      - /opt/docker/data:/source
    ports:
      - 8200:8200
    restart: unless-stopped
    
