---
- name: Ensure Chocolatey is installed
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: "{{ chocolatey_state }}"

- name: Ensure all Chocolatey packages are up to date
  chocolatey.chocolatey.win_chocolatey:
    name: all
    state: latest
