---
- name: Ensure Vault directory exists
  ansible.builtin.file:
    path: "{{ vault_dir }}"
    state: directory
    mode: '0755'

- name: Deploy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ vault_dir }}/docker-compose.yml"
    mode: '0644'

- name: Launch Vault stack
  community.docker.docker_compose_v2:
    project_src: "{{ vault_dir }}"
    state: present
  register: vault_compose

- name: Display compose status
  ansible.builtin.debug:
    var: vault_compose
