---
- name: Ensure Semaphore directory exists
  ansible.builtin.file:
    path: "{{ semaphore_dir }}"
    state: directory
    mode: '0755'

- name: Deploy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ semaphore_dir }}/docker-compose.yml"
    mode: '0644'

- name: Launch Semaphore stack
  community.docker.docker_compose:
    project_src: "{{ semaphore_dir }}"
    state: present
  register: semaphore_compose

- name: Display compose status
  ansible.builtin.debug:
    var: semaphore_compose
