FROM debian:latest

LABEL maintainer="votre-email@example.com"

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    curl \
    git \
    cmake \
    zlib1g-dev \
    libboost-system-dev \
    libboost-program-options-dev \
    libpthread-stubs0-dev \
    libfuse-dev \
    libudev-dev \
    build-essential \
    fuse \
    expect \
    && apt-get clean

RUN git clone https://github.com/pcloudcom/console-client.git /opt/console-client

WORKDIR /opt/console-client/pCloudCC/lib/pclsync
RUN make clean && make fs

WORKDIR /opt/console-client/pCloudCC/lib/mbedtls
RUN cmake . && make clean && make

WORKDIR /opt/console-client/pCloudCC
RUN cmake . && make && make install && ldconfig

RUN mknod /dev/fuse -m 666 c 10 229

ENV PCLOUD_USERNAME=""
ENV PCLOUD_PASSWORD=""

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
