version: '3.8'

services:
  pcloud:
    build: .
    environment:
      - PCLOUD_USERNAME=${PCLOUD_USERNAME}
      - PCLOUD_PASSWORD=${PCLOUD_PASSWORD}
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
      - MKNOD
    devices:
      - /dev/fuse
    entrypoint: ["/entrypoint.sh"]
