---
- name: Ensure Zerotier directory exists
  ansible.builtin.file:
    path: "{{ zerotier_dir }}"
    state: directory
    mode: '0755'

- name: Deploy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ zerotier_dir }}/docker-compose.yml"
    mode: '0644'

- name: Launch Zerotier stack
  community.docker.docker_compose_v2:
    project_src: "{{ zerotier_dir }}"
    state: present
  register: zerotier_compose

- name: Display compose status
  ansible.builtin.debug:
    var: zerotier_compose
