---
- name: Add Zerotier GPG key
  ansible.builtin.apt_key:
    url: https://download.zerotier.com/contact%40zerotier.com.gpg
    state: present
  become: true

- name: Add Zerotier repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.zerotier.com/debian/{{ ansible_distribution_release | lower }} {{ ansible_distribution_release | lower }} main"
    filename: zerotier
    state: present
    update_cache: true
  become: true

- name: Install zerotier-one package
  ansible.builtin.apt:
    name: zerotier-one
    state: present
    update_cache: true
  become: true

- name: Enable and start Zerotier service
  ansible.builtin.systemd:
    name: zerotier-one
    enabled: true
    state: started
  become: true

- name: Join Zerotier network if configured
  ansible.builtin.command: "zerotier-cli join {{ zerotier_network_id }}"
  args:
    creates: "/var/lib/zerotier-one/networks.d/{{ zerotier_network_id }}.conf"
  when: zerotier_network_id | length > 0
  become: true
  changed_when: false

