# ansible/playbooks/roles/docker_dynamic_bind/tasks/main.yml
---
- name: Detect ZeroTier interface
  ansible.builtin.set_fact:
    zt_interface: "{{ ansible_interfaces | select('match', '^zt') | list | first | default('') }}"

- name: Fail if ZeroTier interface is not found
  ansible.builtin.fail:
    msg: "No ZeroTier interface found"
  when: zt_interface | length == 0

- name: Gather ZeroTier IP address
  ansible.builtin.set_fact:
    zt_ip: "{{ hostvars[inventory_hostname]['ansible_' + zt_interface]['ipv4']['address'] }}"

- name: Deploy docker-compose override
  ansible.builtin.template:
    src: docker-compose.override.yml.j2
    dest: /opt/oasis/docker-compose.override.yml
    mode: '0600'
  notify: Restart containers
