---
- name: Install fail2ban package
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
  become: true

- name: Deploy fail2ban configuration
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  become: true

- name: Ensure fail2ban is enabled and running
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started
  become: true
