---
pcloud_mount_point: "/mnt/pcloud"
pcloud_config_file: "/etc/rclone/rclone.conf"
pcloud_log_file: "/var/log/rclone.log"
pcloud_service_file: "/etc/systemd/system/rclone-pcloud.service"
pcloud_group: "pcloud_users"
pcloud_gid: "1001"
pcloud_token: ""

pcloud_rclone_options:
  - "--allow-other"
  - "--uid 0"
  - "--gid 1000"
  - "--file-perms 0660"
  - "--dir-perms 0770"
  - "--vfs-cache-mode full"
  - "--cache-dir /var/cache/rclone"
  - "--dir-cache-time 5m"
  - "--log-level INFO"
