---
- name: Validate bind configuration
  ansible.builtin.command: >-
    docker compose exec -T bind named-checkconf /etc/bind/named.conf
  args:
    chdir: "{{ bind_dns_compose_path }}"
  changed_when: false
  listen: restart bind

- name: Restart bind
  ansible.builtin.command: docker compose restart bind
  args:
    chdir: "{{ bind_dns_compose_path }}"
  changed_when: true
  listen: restart bind
