# ansible/playbooks/roles/bind_dns/handlers/main.yml
---
- name: restart bind
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ bind_compose_path }}"
  register: compose_restart
  changed_when: "'Recreating' in compose_restart.stdout or 'Creating' in compose_restart.stdout or 'Starting' in compose_restart.stdout"
