---
netbox_compact_stack_confirmed: false
netbox_version: "latest"
netbox_dir: "/opt/netbox"
netbox_db_name: "netbox"
netbox_db_user: "netbox"
netbox_db_password: "{{ lookup('ansible.builtin.env', 'NETBOX_DB_PASSWORD') }}"
netbox_redis_password: "{{ lookup('ansible.builtin.env', 'NETBOX_REDIS_PASSWORD') }}"
netbox_secret_key: "{{ lookup('ansible.builtin.env', 'NETBOX_SECRET_KEY') }}"
netbox_port: 8080
