---
all:
  children:
    linux:
      children:
        infraforge_vps: {}
    infraforge_vps:
      hosts:
        infraforge-vps:
          ansible_connection: ssh
          ansible_host: 10.78.0.1
          ansible_user: debian
          ansible_ssh_private_key_file: /run/semaphore-runner/id_ed25519
          ansible_ssh_common_args: >-
            -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes
            -o UserKnownHostsFile=/run/semaphore-runner/known_hosts
