---
- name: Install Chocolatey and desktop apps
  hosts: windows
  roles:
    - chocolatey
    - vlc
    - chrome
    - thunderbird
    - notepadplusplus
    - git
    - sevenzip
    - everything
    - pcloud_win
    - zerotier
    - signal
