# ansible/playbooks/roles/docker_dynamic_bind/handlers/main.yml
---
- name: Restart containers
  ansible.builtin.command:
    cmd: docker compose -f /opt/oasis/docker-compose.yml -f /opt/oasis/docker-compose.override.yml up -d
  become: true
  changed_when: false
