---
- name: Detect ZeroTier interface
  ansible.builtin.set_fact:
    portainer_zerotier_interface: >-
      {{
        ansible_interfaces
        | select('match', '^zt')
        | list
        | first
        | default('')
      }}

- name: Fail if ZeroTier interface not found
  ansible.builtin.fail:
    msg: "No ZeroTier interface found"
  when: portainer_zerotier_interface | length == 0

- name: Gather ZeroTier IP address
  ansible.builtin.set_fact:
    portainer_zerotier_ip: >-
      {{
        hostvars[inventory_hostname]
        ['ansible_' ~ portainer_zerotier_interface]
        ['ipv4']['address']
      }}

- name: Ensure Portainer directory exists
  ansible.builtin.file:
    path: "{{ portainer_dir }}"
    state: directory
    mode: '0755'

- name: Deploy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ portainer_dir }}/docker-compose.yml"
    mode: '0644'

- name: Launch Portainer stack
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_dir }}"
    state: present
    pull: always
  register: portainer_compose

- name: Display compose status
  ansible.builtin.debug:
    var: portainer_compose
