# ansible/roles/argocd/tasks/main.yml
---
- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - curl
      - kubectl
    state: present
    update_cache: yes
  become: yes

- name: Download ArgoCD CLI
  ansible.builtin.get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/v{{ argocd_version }}/argocd-linux-amd64"
    dest: /usr/local/bin/argocd
    mode: '0755'
  become: yes

- name: Create ArgoCD namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: argocd
    state: present

- name: Install ArgoCD in cluster
  ansible.builtin.shell: |
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v{{ argocd_version }}/manifests/install.yaml
  args:
    executable: /bin/bash
  become: yes
