---
- name: Ensure Prometheus directory exists
  ansible.builtin.file:
    path: "{{ prometheus_dir }}"
    state: directory
    mode: '0755'

- name: Deploy Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir }}/prometheus.yml"
    mode: '0644'

- name: Deploy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_dir }}/docker-compose.yml"
    mode: '0644'

- name: Launch Prometheus stack
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_dir }}"
    state: present
  register: prometheus_compose

- name: Display compose status
  ansible.builtin.debug:
    var: prometheus_compose
