name: Build Services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - heimdall
          - uptime-kuma
          - duplicati
          - jdownloader
    steps:
      # Étape 1 : Get the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configure Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 3 : Build each service
      - name: Build ${{ matrix.service }} Docker Image
        run: docker compose -f docker-compose/${{ matrix.service }}/docker-compose.yml build
