name: Build and Push Docker Image with Packer

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Tag for the Docker image (e.g., latest, v1.0.0)'
        required: false
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Initialize Packer
        run: |
          cd packer
          packer init docker-image.pkr.hcl

      - name: Verify Packer Plugins
        run: |
          packer plugins installed

      - name: Build Docker Image with Packer
        run: |
          cd packer
          packer build -var "docker_tag=${{ github.event.inputs.docker_tag }}-${{ github.sha }}" docker-image.pkr.hcl

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: richeju
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Verify Docker Image
        run: |
          docker images ghcr.io/richeju/debian12-server:${{ github.event.inputs.docker_tag }}-${{ github.sha }}

      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push ghcr.io/richeju/debian12-server:${{ github.event.inputs.docker_tag }}-${{ github.sha }}
