---
name: Apply Updates

'on':
  schedule:
    - cron: '30 4 * * 0'
  workflow_dispatch:
  push:
    paths:
      - 'ansible/playbooks/roles/apt/**'
      - 'ansible/playbooks/apply_updates.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible and ansible-lint
        run: |
          pip install ansible ansible-lint
      - name: Run ansible-lint
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: ansible-lint ansible/

  deploy:
    needs: lint
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml
      - name: Execute apply_updates playbook
        working-directory: ansible
        run: |
          ansible-playbook playbooks/apply_updates.yml -i inventories/production/hosts.yml --become
