---
name: Deploy Semaphore

on:
  schedule:
    - cron: '45 4 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'ansible/playbooks/roles/semaphore/**'
      - 'ansible/site.yml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml
      - name: Execute playbook
        working-directory: ansible
        run: |
          ansible-playbook site.yml -i inventories/production/hosts.yml \
            --tags semaphore --become
