---
name: Deploy NetBox

'on':
  push:
    paths:
      - 'ansible/playbooks/roles/netbox/**'
      - 'ansible/playbooks/install_netbox.yml'
  workflow_dispatch:
  schedule:
    - cron: '25 3 * * 1'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml
      - name: Execute playbook
        working-directory: ansible
        env:
          NETBOX_DB_PASSWORD: ${{ secrets.NETBOX_DB_PASSWORD }}
          NETBOX_REDIS_PASSWORD: ${{ secrets.NETBOX_REDIS_PASSWORD }}
          NETBOX_SECRET_KEY: ${{ secrets.NETBOX_SECRET_KEY }}
          ANSIBLE_DISPLAY_ARGS_TO_STDOUT: 'false'
        run: |
          ansible-playbook playbooks/install_netbox.yml \
            -i inventories/production/hosts.yml \
            -e "netbox_db_password=${NETBOX_DB_PASSWORD}" \
            -e "netbox_redis_password=${NETBOX_REDIS_PASSWORD}" \
            -e "netbox_secret_key=${NETBOX_SECRET_KEY}" \
            --become
