---
name: Apply Updates

'on':
  schedule:
    - cron: '30 4 * * 0'
  workflow_dispatch:
  push:
    paths:
      - 'ansible/playbooks/roles/apt/**'
      - 'ansible/playbooks/apply_updates.yml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml
      - name: Execute apply_updates playbook
        working-directory: ansible
        run: |
          ansible-playbook playbooks/apply_updates.yml \
            -i inventories/production/hosts.yml --become
