name: Deploy with Ansible

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    if: github.repository == 'richeju/orchestrationoasis'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible
      - name: Run Ansible Playbook
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
        run: |
          echo "$ANSIBLE_VAULT_PASSWORD" > vault_pass.txt
          cd ansible/playbooks
          ansible-playbook install_pcloud.yml --vault-password-file ../../vault_pass.txt
          rm ../../vault_pass.txt
