---
name: Deploy YubiKey

'on':
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '45 2 * * 3'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml
      - name: Execute playbook
        working-directory: ansible
        env:
          ANSIBLE_DISPLAY_ARGS_TO_STDOUT: 'false'
        run: |
          ansible-playbook playbooks/install_yubikey.yml \
            -i inventories/production/hosts.yml \
            --become
