name: Lint Code Base

on:
 push:
 branches: [ main ]
 pull_request:
 branches: [ main ]

jobs:
 lint:
 runs-on: ubuntu-latest
 if: github.repository == 'richeju/orchestrationoasis'
 steps:
 - name: Checkout code
 uses: actions/checkout@v3
 - name: Set up Ansible Vault password
 env:
 ANSIBLE_VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
 run: echo "$ANSIBLE_VAULT_PASSWORD" > vault_pass.txt
 - name: Run Super-Linter
 uses: super-linter/super-linter@v5
 env:
 VALIDATE_ALL_CODEBASE: true
 DEFAULT_BRANCH: main
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 ANSIBLE_VAULT_PASSWORD_FILE: vault_pass.txt
 - name: Clean up
 if: always()
 run: rm vault_pass.txt
 
