---
name: Lint

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install lint dependencies
        run: |
          pip install ansible ansible-lint yamllint

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml || true

      - name: Run yamllint
        run: |
          yamllint -d '{extends: relaxed}' .

      - name: Run ansible-lint
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: ansible-lint ansible

      - name: Run Super-Linter
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_ANSIBLE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
