name: Security Scan

on:
  push:
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: fs
          security-checks: vuln,config,secret
          ignore-unfixed: true
          exit-code: '1'
          severity: HIGH,CRITICAL
